apiVersion: v1
kind: Service
metadata:
  name: http-server-ep
  namespace: demo
  labels:
    app: http-server
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: http-server
